services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: jovyan
      POSTGRES_PASSWORD: jovyan
      POSTGRES_DB: dwh
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jovyan"]
      interval: 5s
      retries: 5

  airflow:
    image: apache/airflow:3.1.0-python3.11
    container_name: airflow
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://jovyan:jovyan@postgres:5432/dwh
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: "admin:admin"
      AIRFLOW_VAR_CDM_DDL_FILES_PATH: "/opt/airflow/dags/cdm/ddl"
      AIRFLOW_VAR_DDS_DDL_FILES_PATH: "/opt/airflow/dags/dds/ddl"
      AIRFLOW_VAR_STG_DDL_FILES_PATH: "/opt/airflow/dags/stg/ddl"
      AIRFLOW_CONN_PG_DWH_CONNECTION: "postgres://jovyan:jovyan@postgres:5432/dwh"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "airflow db migrate &&
               airflow api-server &
               airflow dag-processor &
               airflow scheduler"

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.0
    container_name: dbt
    platform: linux/amd64
    working_dir: /usr/app
    volumes:
      - ./dbt:/usr/app
    environment:
      DBT_PROFILES_DIR: /usr/app
    depends_on:
      - postgres

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: dwh
      MB_DB_PORT: 5432
      MB_DB_USER: jovyan
      MB_DB_PASS: jovyan
      MB_DB_HOST: postgres
    depends_on:
      - postgres

volumes:
  postgres_data:
  logs:
  plugins: