FROM apache/airflow:3.1.3-python3.13

USER root

RUN chown -R airflow:root /usr/local/lib/python3.13/site-packages

USER airflow

RUN pip install --user --no-cache-dir dbt-postgres==1.9.1

WORKDIR /opt/airflow